[build]
builder = "dockerfile"
dockerfilePath = "packages/server/Dockerfile"
buildContext = "packages/server"

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
healthcheckPath = "/v1/health"
